package com.example.myapplication.Model.Pojo



import com.example.myapplication.Contract.MyInterface


class DataModel() : MyInterface.ModelInterface
{

    private var arrayList: ArrayList<String>? = null
    private var presenter: MyInterface.Presenter? = null
    override fun getValue()
    {
        getFullList()
        updateList()
    }

    //updating the Array List after each operation
    override fun updateList()
    {
        presenter?.getCountryLists(arrayList!!)
    }


    //initializing the model class with the same object of presenter 
    fun initData(presenter: MyInterface.Presenter)
    {
        this.presenter = presenter
        getValue()
    }
    private fun getFullList()
    {
        arrayList=ArrayList()
        createListOfEurope()
        createListOfAfrica()
        createListOfAmerica()
        cityListOfAsia()
        cityListOfAustralian()
        cityListOfOceania()
    }
    private fun createListOfEurope()
    {
        arrayList?.add("London")
        arrayList?.add("Berlin")
        arrayList?.add("Mariehamn")
        arrayList?.add("Tirana")
        arrayList?.add("Andorra la Vella")
        arrayList?.add("Vienna")
        arrayList?.add("Minsk")
        arrayList?.add("Brussels")
        arrayList?.add("Sarajevo")
        arrayList?.add("Sofia")
        arrayList?.add("Zagreb")
        arrayList?.add("Prague")
        arrayList?.add("Copenhagen")
        arrayList?.add("Tallinn")
        arrayList?.add("Tórshavn")
        arrayList?.add("Helsinki")
        arrayList?.add("Paris")
        arrayList?.add("Gibraltar")
        arrayList?.add("Athens")
        arrayList?.add("Saint Peter Port")
        arrayList?.add("Budapest")
        arrayList?.add("Reykjavík")
        arrayList?.add("Dublin")
        arrayList?.add("Douglas")
        arrayList?.add("Rome")
        arrayList?.add("Saint Helier")
        arrayList?.add("Pristina")
        arrayList?.add("Riga")
        arrayList?.add("Vaduz")
        arrayList?.add("Vilnius")
        arrayList?.add("Luxembourg")
        arrayList?.add("Valletta")
        arrayList?.add("Chisinau")
        arrayList?.add("Monaco")
        arrayList?.add("Podgorica")
        arrayList?.add("Amsterdam")
        arrayList?.add("Skopje")
        arrayList?.add("Oslo")
        arrayList?.add("Warsaw")
        arrayList?.add("Lisbon")
        arrayList?.add("Bucharest")
        arrayList?.add("Moscow")
        arrayList?.add("San Marino")
        arrayList?.add("Belgrade")
        arrayList?.add("Bratislava")
        arrayList?.add("Ljubljana")
        arrayList?.add("Madrid")
        arrayList?.add("Longyearbyen")
        arrayList?.add("Stockholm")
        arrayList?.add("Bern")
        arrayList?.add("Kiev")
    }
    private fun createListOfAfrica()
    {
        arrayList?.add("Algiers")
        arrayList?.add("Luanda")
        arrayList?.add("Porto-Novo")
        arrayList?.add("Gaborone")
        arrayList?.add("Ouagadougou")
        arrayList?.add("Bujumbura")
        arrayList?.add("Yaoundé")
        arrayList?.add("Praia")
        arrayList?.add("Bangui")
        arrayList?.add("N'Djamena")
        arrayList?.add("Moroni")
        arrayList?.add("Kinshasa")
        arrayList?.add("Djibouti")
        arrayList?.add("Cairo")
        arrayList?.add("Malabo")
        arrayList?.add("Asmara")
        arrayList?.add("Mbabane")
        arrayList?.add("Addis Ababa")
        arrayList?.add("Libreville")
        arrayList?.add("Banjul")
        arrayList?.add("Accra")
        arrayList?.add("Conakry")
        arrayList?.add("Bissau")
        arrayList?.add("Yamoussoukro")
        arrayList?.add("Nairobi")
        arrayList?.add("Maseru")
        arrayList?.add("Monrovia")
        arrayList?.add("Tripoli")
        arrayList?.add("Antananarivo")
        arrayList?.add("Lilongwe")
        arrayList?.add("Bamako")
        arrayList?.add("Nouakchott")
        arrayList?.add("Port Louis")
        arrayList?.add("Mamoudzou")
        arrayList?.add("Rabat")
        arrayList?.add("Maputo")
        arrayList?.add("Windhoek")
        arrayList?.add("Niamey")
        arrayList?.add("Abuja")
        arrayList?.add("Saint-Denis")
        arrayList?.add("Kigali")
        arrayList?.add("Jamestown")
        arrayList?.add("São Tomé")
        arrayList?.add("Dakar")
        arrayList?.add("Victoria")
        arrayList?.add("Freetown")
        arrayList?.add("Mogadishu")
        arrayList?.add("Pretoria")
        arrayList?.add("Juba")
        arrayList?.add("Khartoum")
        arrayList?.add("Dodoma")
        arrayList?.add("Lomé")
        arrayList?.add("Tunis")
        arrayList?.add("El Aaiún")
        arrayList?.add("Lusaka")
        arrayList?.add("Harare")
    }
    private fun createListOfAmerica()
    {
        arrayList?.add("The Valley")
        arrayList?.add("Saint John’s")
        arrayList?.add("Buenos Aires")
        arrayList?.add("Oranjestad")
        arrayList?.add("Nassau")
        arrayList?.add("Bridgetown")
        arrayList?.add("Belmopan")
        arrayList?.add("Hamilton")
        arrayList?.add("Sucre")
        arrayList?.add("Brasília")
        arrayList?.add("Road Town")
        arrayList?.add("Ottawa")
        arrayList?.add("George Town")
        arrayList?.add("Santiago")
        arrayList?.add("Bogotá")
        arrayList?.add("San José")
        arrayList?.add("Havana")
        arrayList?.add("Willemstad")
        arrayList?.add("Roseau")
        arrayList?.add("Santo Domingo")
        arrayList?.add("Quito")
        arrayList?.add("San Salvador")
        arrayList?.add("Stanley")
        arrayList?.add("Cayenne")
        arrayList?.add("Nuuk")
        arrayList?.add("Saint George's")
        arrayList?.add("Basse-Terre")
        arrayList?.add("Guatemala City")
        arrayList?.add("Georgetown")
        arrayList?.add("Port-au-Prince")
        arrayList?.add("Tegucigalpa")
        arrayList?.add("Kingston")
        arrayList?.add("Fort-de-France")
        arrayList?.add("Mexico City")
        arrayList?.add("Brades")
        arrayList?.add("Managua")
        arrayList?.add("Panama City")
        arrayList?.add("Asunción")
        arrayList?.add("Lima")
        arrayList?.add("San Juan")
        arrayList?.add("Gustavia")
        arrayList?.add("Basseterre")
        arrayList?.add("Castries")
        arrayList?.add("Marigot")
        arrayList?.add("Saint-Pierre")
        arrayList?.add("Kingstown")
        arrayList?.add("Philipsburg")
        arrayList?.add("King Edward Point")
        arrayList?.add("Paramaribo")
        arrayList?.add("Port-of-Spain")
        arrayList?.add("Cockburn Town")
        arrayList?.add("Washington, D.C.")
        arrayList?.add("Montevideo")
        arrayList?.add("Caracas")
        arrayList?.add("Charlotte Amalie")
    }
    private fun cityListOfAsia()
    {
        arrayList?.add("Kabul")
        arrayList?.add("Yerevan")
        arrayList?.add("Baku")
        arrayList?.add("Manama")
        arrayList?.add("Dhaka")
        arrayList?.add("Thimphu")
        arrayList?.add("Bandar Seri Begawan")
        arrayList?.add("Nay Pyi Taw")
        arrayList?.add("Phnom Penh")
        arrayList?.add("Beijing")
        arrayList?.add("Nicosia")
        arrayList?.add("Dili")
        arrayList?.add("Tbilisi")
        arrayList?.add("Hong Kong")
        arrayList?.add("New Delhi")
        arrayList?.add("Jakarta")
        arrayList?.add("Tehran")
        arrayList?.add("Baghdad")
        arrayList?.add("Tokyo")
        arrayList?.add("Amman")
        arrayList?.add("Nursultan")
        arrayList?.add("Kuwait City")
        arrayList?.add("Bishkek")
        arrayList?.add("Vientiane")
        arrayList?.add("Beirut")
        arrayList?.add("Concelho de Macau")
        arrayList?.add("Kuala Lumpur")
        arrayList?.add("Malé")
        arrayList?.add("Ulaanbaatar")
        arrayList?.add("Kathmandu")
        arrayList?.add("Pyongyang")
        arrayList?.add("Muscat")
        arrayList?.add("Islamabad")
        arrayList?.add("Ramallah")
        arrayList?.add("Manila")
        arrayList?.add("Doha")
        arrayList?.add("Riyadh")
        arrayList?.add("Singapore")
        arrayList?.add("Seoul")
        arrayList?.add("Colombo")
        arrayList?.add("Damascus")
        arrayList?.add("Taipei")
        arrayList?.add("Dushanbe")
        arrayList?.add("Bangkok")
        arrayList?.add("Ankara")
        arrayList?.add("Ashgabat")
        arrayList?.add("Abu Dhabi")
        arrayList?.add("Tashkent")
        arrayList?.add("Hanoi")
        arrayList?.add("Sanaa")
    }
    private fun cityListOfAustralian()
    {
        arrayList?.add("Canberra")
        arrayList?.add("Flying Fish Cove")
        arrayList?.add("West Island")
        arrayList?.add("Wellington")
        arrayList?.add("Kingston")
    }
    private fun cityListOfOceania()
    {
        arrayList?.add("Pago Pago")
        arrayList?.add("Avarua")
        arrayList?.add("Suva")
        arrayList?.add("Papeete")
        arrayList?.add("Hagåtña")
        arrayList?.add("Tarawa")
        arrayList?.add("Majuro")
        arrayList?.add("Yaren")
        arrayList?.add("Nouméa")
        arrayList?.add("Alofi")
        arrayList?.add("Saipan")
        arrayList?.add("Port Moresby")
        arrayList?.add("Adamstown")
        arrayList?.add("Apia")
        arrayList?.add("Honiara")
        arrayList?.add("Nuku‘alofa")
        arrayList?.add("Port-Vila")
        arrayList?.add("Funafuti")
        arrayList?.add("Mata-Utu")

    }
}